Update pr-develop.yml

diff --git a/.githib/workflows/pr-develop.yml b/.githib/workflows/pr-develop.yml
--- a/.githib/workflows/pr-develop.yml
+++ b/.githib/workflows/pr-develop.yml
@@ -1,46 +1,53 @@
 name: Pull Request to Develop
-'on':
+
+on:
   pull_request:
-    branches:
-      - develop
+    branches: [ develop ]
+
 jobs:
   validate_pull_request:
     runs-on: ubuntu-latest
+
     steps:
-      - uses: actions/checkout@v2
-      - name: Install Salesforce CLI
-        run: >
-          wget
-          https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
+    - uses: actions/checkout@v2
 
-          mkdir sfdx-cli
+    - name: Install Salesforce CLI
+      run: |
+        wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
+        mkdir ~/sfdx
+        tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
+        echo "$HOME/sfdx/bin" >> $GITHUB_PATH
+        ~/sfdx/bin/sfdx version
 
-          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
+    - name: Install jq
+      run: |
+        sudo apt-get install jq
+    
+    - name: Populate auth file
+      shell: bash
+      run: 'echo ${{secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt'
+    
+    - name: Authenticate Dev Hub
+      run: 'sfdx force:auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d'
 
-          ./sfdx-cli/install
-      - name: Install jq
-        run: |
-          sudo apt-get install jq
-      - name: Populate auth file
-        shell: bash
-        run: 'echo ${{secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt'
-      - name: Authenticate Dev Hub
-        run: 'sfdx force:auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d'
-      - name: Create scratch org
-        run: >-
-          sfdx force:org:create -f config/project-scratch-def.json -a ci_scratch
-          -s -d 1
-      - name: Push source to scratch org
-        run: 'sfdx force:source:push'
-      - name: Check code coverage
-        run: >
-          sf apex test run -o ci_scratch --codecoverage --resultformat json
-          --synchronous --testlevel RunLocalTests --wait 10 > tests.json
+    - name: Create scratch org
+      run: 'sf org create scratch -f config/project-scratch-def.json -a ci_scratch -y 1'
+    
+    - name: Push source to scratch org
+      run: 'sfdx force:source:push -o ci_scratch'
+    
+    - name:  Check code coverage
+      shell: bash
+      run:  |
+            coverage=$(sf apex test run --code-coverage --result-format human --synchronous -o ci_scratch --test-level RunLocalTests --wait 10)
+            if [ "$coverage" -lt 85 ]; then
+            echo "Failed due to less code coverage. Current coverage: $coverage%"
+            exit 1
+            else
+            echo "Code coverage is sufficient. Current coverage: $coverage%"
+            exit 0
+            fi
 
-          coverage=$(jq .result.summary.orgWideCoverage tests.json | grep -Eo
-          "[[:digit:]]+")
-
-          test $coverage -ge 75
-      - name: Delete scratch org
-        if: always()
-        run: 'sfdx force:org:delete -p -u ci_scratch'
+    - name: Delete scratch org
+      if: always()
+      run: 'sf org delete scratch -p -o ci_scratch'
